#!/usr/bin/env node
/**
 * scripts/gen-models.ts — generate src/components/calculator/models.generated.ts
 * from the verified hp/mapping/mapping.json (single source of truth).
 *
 *   pnpm tsx scripts/gen-models.ts
 *
 * Why: faceplate rendering AND keystroke dispatch must both come from the same
 * data, so legends can never drift from behaviour (PRD FR-MODEL-1/2). This reads
 * the machine-readable map and emits a typed, ready-to-import module.
 *
 * mapping.json shape (per model):
 *   { <MODEL>: { keys: [ { row, keypad, primary,
 *       presses: [ { access, prefix, color, function, description } ] } ] } }
 *
 * NOTE: mapping.json carries legends + functions + shift COLOURS + row, but not
 * the physical column index or double-height spans. Those are layout facts that
 * live in hp/layouts/<MODEL>.md. Keep a small per-model LAYOUT table here (cols
 * per row, ENTER span) — it's the only hand-maintained bit, and it's tiny.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

type Press = { access: string; prefix: string; color?: string; function: string; description?: string };
type RawKey = { row: string; keypad: string | null; primary: string; presses: Press[] };
type Mapping = Record<string, { keys: RawKey[] }>;

const ROOT = resolve(import.meta.dirname, "..");
const mapping: Mapping = JSON.parse(readFileSync(resolve(ROOT, "hp/mapping/mapping.json"), "utf8"));

// ---- family + layout facts (from hp/layouts/*.md) ---------------------------
type Family = "voyager" | "classic" | "rpl";
const MODEL_META: Record<string, { family: Family; sub: string; angle: boolean; cols: number; enterCol?: number }> = {
  "HP-35":  { family: "classic", sub: "RPN · LED",        angle: false, cols: 5 },
  "HP-12C": { family: "voyager", sub: "RPN · FINANCIAL",  angle: false, cols: 10, enterCol: 6 },
  "HP-15C": { family: "voyager", sub: "RPN · SCIENTIFIC", angle: true,  cols: 10, enterCol: 6 },
  "HP-48G": { family: "rpl",     sub: "RPL · GRAPHING",   angle: true,  cols: 6 },
};

const pick = (presses: Press[], access: string) => presses.find((p) => p.access === access)?.function ?? "";
const kindOf = (primary: string): string => {
  if (/^[0-9]$/.test(primary)) return "digit";
  if (["+", "−", "×", "÷"].includes(primary)) return "arith";
  if (primary === "ENTER") return "enter";
  if (primary === "f") return "pf";
  if (primary === "g") return "pg";
  if (primary === "ON") return "on";
  return "std";
};

// ---- build Voyager keys (col derived from position within its row) ----------
function buildVoyager(model: string, keys: RawKey[]) {
  const meta = MODEL_META[model];
  const byRow = new Map<string, RawKey[]>();
  for (const k of keys) (byRow.get(k.row) ?? byRow.set(k.row, []).get(k.row)!).push(k);
  const out: string[] = [];
  for (const [row, rowKeys] of [...byRow.entries()].sort()) {
    rowKeys.forEach((k, i) => {
      const col = i + 1;
      const rowSpan = k.primary === "ENTER" ? 2 : 1;
      out.push(
        `  v(${J(k.primary)},${J(pick(k.presses, "f"))},${J(pick(k.presses, "g"))},${col},${row},${J(kindOf(k.primary))}${rowSpan > 1 ? `,${rowSpan}` : ""}),`
      );
    });
  }
  return out.join("\n");
}

const J = (s: string) => JSON.stringify(s);

// ---- emit -------------------------------------------------------------------
let body = `// AUTO-GENERATED by scripts/gen-models.ts from hp/mapping/mapping.json — do not edit.\n`;
body += `import type { Model, VoyagerKey } from "./models";\n\n`;
body += `const v = (primary:string,f:string,g:string,col:number,row:number,kind:VoyagerKey["kind"],rowSpan=1):VoyagerKey => ({primary,f,g,col,row,kind:kind as VoyagerKey["kind"],rowSpan});\n\n`;

for (const model of Object.keys(MODEL_META)) {
  const meta = MODEL_META[model];
  const raw = mapping[model];
  if (!raw) { console.warn(`! ${model} missing from mapping.json — skipped`); continue; }
  if (meta.family === "voyager") {
    body += `const ${ident(model)}: VoyagerKey[] = [\n${buildVoyager(model, raw.keys)}\n];\n\n`;
  } else {
    // classic (HP-35) + rpl (HP-48G) have irregular column widths / extra shift
    // layers; keep their row arrays authored in models.ts. The generator still
    // VALIDATES them against mapping.json below.
    body += `// ${model}: ${meta.family} layout authored in models.ts (irregular widths).\n\n`;
  }
}

body += `export const GENERATED_VOYAGER: Record<string, VoyagerKey[]> = { ${Object.keys(MODEL_META).filter((m) => MODEL_META[m].family === "voyager").map(ident).map((n, i, a) => `${JSON.stringify(voyagerName(n))}: ${n}`).join(", ")} };\n`;

function ident(model: string) { return model.replace(/[^A-Za-z0-9]/g, "_"); }
function voyagerName(id: string) { return id.replace(/_/g, "-"); }

writeFileSync(resolve(ROOT, "src/components/calculator/models.generated.ts"), body);
console.log("✓ wrote src/components/calculator/models.generated.ts");

// ---- validation: every authored legend must exist in mapping.json -----------
// (Run this against models.ts in CI to catch drift. Left as a TODO hook:)
//   for each authored key -> assert mapping[model] has a press whose function
//   matches primary/f/g; report mismatches as errors.
