#!/usr/bin/env node
/**
 * scripts/gen-models.ts — generate src/components/calculator/models.generated.ts
 * from the verified hp/mapping/mapping.json (single source of truth for the
 * Voyager faceplates). Run: `pnpm gen:models`.
 *
 * Why: faceplate rendering AND keystroke dispatch must come from the same data,
 * so legends can never drift from behaviour (PRD FR-MODEL-1/2). Voyager
 * (HP-12C / HP-15C) has a regular 4x10 grid and is fully derived here. Classic
 * (HP-35) and RPL (HP-48G) have irregular column widths / extra shift layers and
 * stay authored in models.ts.
 *
 * mapping.json shape (per model): { <MODEL>: { keys: [ { row, primary,
 *   presses: [ { access, function, … } ] } ] } }. It carries legends, functions,
 * shift colours and row — but not the physical column or double-height spans.
 * Column = position within the row; the tall ENTER spans 2 rows and its lower
 * half is a placeholder cell in mapping.json (see isEnterCont).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

type Press = { access: string; function: string };
type RawKey = { row: string; primary: string; presses: Press[] };
type Mapping = Record<string, { keys: RawKey[] }>;

const ROOT = resolve(import.meta.dirname, "..");
const mapping: Mapping = JSON.parse(
  readFileSync(resolve(ROOT, "hp/mapping/mapping.json"), "utf8"),
);

const VOYAGER_MODELS = ["HP-12C", "HP-15C"] as const;

const pick = (presses: Press[], access: string) =>
  presses.find((p) => p.access === access)?.function ?? "";

const ARITH = new Set(["+", "−", "×", "÷"]); // + − × ÷
function kindOf(primary: string): string {
  if (/^[0-9]$/.test(primary)) return "digit";
  if (ARITH.has(primary)) return "arith";
  if (primary === "ENTER") return "enter";
  if (primary === "f") return "pf";
  if (primary === "g") return "pg";
  if (primary === "ON") return "on";
  return "std";
}

// Lower half of the double-height ENTER key: HP-12C encodes it as
// "ENTER (cont.)", HP-15C as "[ENTER↑]". It occupies a grid cell that the real
// ENTER's rowSpan already covers, so it must NOT be emitted as its own key —
// but it still counts for column numbering (that is what leaves the gap).
const isEnterCont = (p: string) =>
  p !== "ENTER" && /ENTER|↑/.test(p) && (/\(cont/i.test(p) || p.startsWith("["));

const J = (s: string) => JSON.stringify(s);

function buildVoyager(keys: RawKey[]): string {
  const byRow = new Map<string, RawKey[]>();
  for (const k of keys) {
    const list = byRow.get(k.row) ?? [];
    list.push(k);
    byRow.set(k.row, list);
  }
  const lines: string[] = [];
  for (const [row, rowKeys] of [...byRow.entries()].sort()) {
    rowKeys.forEach((k, i) => {
      const col = i + 1; // physical column = position within the row
      if (isEnterCont(k.primary)) return; // covered by ENTER's rowSpan
      const rowSpan = k.primary === "ENTER" ? 2 : 1;
      lines.push(
        `  v(${J(k.primary)},${J(pick(k.presses, "f"))},${J(pick(k.presses, "g"))},${col},${Number(row)},${J(kindOf(k.primary))}${rowSpan > 1 ? `,${rowSpan}` : ""}),`,
      );
    });
  }
  return lines.join("\n");
}

let body = `// AUTO-GENERATED by scripts/gen-models.ts from hp/mapping/mapping.json — do not edit.\n`;
body += `// Regenerate with: pnpm gen:models\n`;
body += `import type { VoyagerKey } from "./models";\n\n`;
body += `const v = (\n`;
body += `  primary: string, f: string, g: string, col: number, row: number,\n`;
body += `  kind: VoyagerKey["kind"], rowSpan = 1,\n`;
body += `): VoyagerKey => ({ primary, f, g, col, row, kind, rowSpan });\n\n`;

const entries: string[] = [];
for (const model of VOYAGER_MODELS) {
  const raw = mapping[model];
  if (!raw) {
    console.warn(`! ${model} missing from mapping.json — skipped`);
    continue;
  }
  const ident = model.replace(/[^A-Za-z0-9]/g, "_");
  body += `const ${ident}: VoyagerKey[] = [\n${buildVoyager(raw.keys)}\n];\n\n`;
  entries.push(`  ${J(model)}: ${ident},`);
}
body += `export const GENERATED_VOYAGER: Record<string, VoyagerKey[]> = {\n${entries.join("\n")}\n};\n`;

const outPath = resolve(ROOT, "src/components/calculator/models.generated.ts");
writeFileSync(outPath, body);
console.log(`✓ wrote ${outPath} (${entries.length} Voyager models)`);
